{
 "title": "Thanos Query",
 "tags": [ "thanos" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "querier",
    "query": "up{job=\"thanos_querier\"}"
   }
  ]
 },
 "panels": [
  { "title": "Thanos Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{job=\"thanos_querier\",instance=\"$querier\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}} {{grpc_method}} {{$querier}}"
    }
   ]
  },
  {
   "title": "Response Time Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_client_handling_seconds_bucket{job=\"thanos_querier\",instance=\"$querier\"}[$interval])) by (grpc_method, le))",
     "legendFormat": "99.99 {{grpc_method}} {{$querier}}"
    }
   ]
  },
  {
   "title": "Thanos Query 99.99 Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(http_request_duration_seconds_bucket{job=\"thanos_querier\",instance=\"$querier\",handler=\"query\"}[$interval])) by ( le))",
     "legendFormat": "instant_query {{$querier}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(http_request_duration_seconds_bucket{job=\"thanos_querier\",instance=\"$querier\",handler=\"query_range\"}[$interval])) by ( le))",
     "legendFormat": "range_query {{$querier}}"
    }
   ]
  },
  {
   "title": "Prometheus Query 99 Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"thanos_querier\",instance=\"$querier\",quantile=\"0.99\"}",
     "legendFormat": "{{ $querier}}{{slice}}"
    }
   ]
  },
  {
   "title": "Prometheus Queries/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_queries{job=\"thanos_querier\",instance=\"$querier\"}",
     "legendFormat": "{{$querier}}"
    }
   ]
  },
  {
   "title": "Gossip info",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "min(thanos_store_node_info{instance=\"$querier\"}) by (external_labels)"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"thanos_querier\",instance=\"$querier\"}",
     "legendFormat": "{{$querier}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$querier\"}",
     "legendFormat": "{{$querier}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"thanos_querier\",instance=\"$querier\"}",
     "legendFormat": "{{quantile}} {{$querier}}"
    }
   ]
  }
 ]
}