groups:
- name: Noderule
  rules:
  - alert: NodeExporterDown
    expr: up{job="node_exporter"} == 0  
    for: 15s
    labels:
      severity: critical
    annotations:
      summary: "Exporter down"
      description: "Node exporter down {{ $labels.instance }} for 15 seconds"
  - alert: OutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Out of memory on {{ $labels.instance }}"
      description: "Node memory is filling up (< 80% left) on {{ $labels.instance }} for one minute"    