# alertmanager.yml
global:
  resolve_timeout: 1d
route:

  group_by: ['alertname']
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a betch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 12h

  # A default receiver
  receiver: "channel1"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: "channel1"
      group_wait: 10s
      group_interval: 
      match_re:
        severity: critical|warning
      continue: true

    - receiver: "channel2"
      group_wait: 10s
      match_re:
        severity: info
      continue: true

receivers:
  - name: "channel1"
    webhook_configs:
      - url: http://localhost:8000/alert-webhook
        send_resolved: true
  - name: "channel2"
    webhook_configs:
      - url: http://a.b.c:8080/send/sms
        send_resolved: true